In [ ]:
import torch
from torch import nn
import matplotlib.pyplot as plt

# Creating a PyTorch Dataset
from torch.utils.data import Dataset
from torch.utils.data import DataLoader
import numpy as np
from Data import train_loader, test_loader



num_epochs = 10000

learning_rate = 10**(-3)

class NeuralNetwork(nn.Module):
    def __init__(self):
        super().__init__()
        self.layers_stack = nn.Sequential(
            nn.Linear(N_nod, N_nod)
        )

    def forward(self, x):
        logits = self.layers_stack(x)
        return logits
    
    



    
    
model = NeuralNetwork()


criterion = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

def train_loop(dataloader, model, criterion, optimizer):
    num_batches = len(dataloader)

    train_loss = 0

    for features, targets in dataloader:
        # Compute prediction and loss
        pred = model(features)
        loss = criterion(pred, targets)

        # Optimization
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        train_loss += loss.item()

    train_loss /= num_batches
    print(f"Train loss: {train_loss:>8f}")

    return train_loss


def test_loop(dataloader, model, criterion):
    size = len(dataloader.dataset)
    num_batches = len(dataloader)

    test_loss = 0

    with torch.no_grad():
        for features, targets in dataloader:
            # Compute prediction and loss
            pred = model(features)
            loss = criterion(pred, targets)

            test_loss += loss.item()


    test_loss /= num_batches
    print(f"Test loss: {test_loss:>8f} \n")

    return test_loss








loss_history = {"train": [], "test": []}

for i in range(num_epochs):
    print(f"Epoch {i+1}")
    train_loss = train_loop(train_loader, model, criterion, optimizer)
    test_loss = test_loop(test_loader, model, criterion)

    loss_history["train"].append(train_loss)
    loss_history["test"].append(test_loss)
print("Done!")


Epochs=[i for i in range(num_epochs)]
plt.figure()
plt.title("learning_rate="+str(learning_rate),fontsize=17)
plt.plot(Epochs,loss_history["train"])
plt.plot(Epochs,loss_history["test"])
plt.legend(["train","test"])
plt.ylabel("MSE",fontsize=17)
plt.xlabel("epoch",fontsize=17)
plt.grid(True)
plt.show()

torch.save(model.state_dict(), "model_weights1.pth")

In [8]:
import torch
from torch import nn
import matplotlib.pyplot as plt

m=torch.nn.Linear(10,10,bias=False)
W=m.weight
print(W)
det=torch.det(W)
print(det)

class LinearNN(nn.Module):
    def __init__(self):
        super().__init__()
        self.layers_stack = nn.Sequential(
            m
        )

    def forward(self, x):
        x_out = self.layers_stack(x)
        return x_out
    

def criterion(x_out):
    return mean(p(x_out)-fullS(x_out))

#p=det*exp(-(Wx)TWx)
#S=sum model.S(x[i-1],x[i])


NameError: name '_C' is not defined

In [ ]:
import torch
from torch import nn
import matplotlib.pyplot as plt

class Action(nn.Module):
    def __init__(self,A):
        super().__init__()
        self.A=A
    
    def forward(self,x):
        y=torch.dot(self.A,x)
        return 1/2 * torch.dot(y,x) 

class CustomLoss(nn.Module):
    def __init__(self):
        super(CustomLoss, self).__init__()

    def forward(self, x, act, model):
        loss=0
        M=len(x)
        for i in range(M)
            loss+=act(x[i])
        loss=loss/M
        det=torch.det(model.weight)
        Log=torch.log(torch.abs(det))
        loss=loss-log
        return loss
    
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)
loss_fn = CustomLoss()
for epoch in range(num_epochs):
    # Forward pass
    outputs = model(inputs)
    loss = loss_fn(outputs, targets)

    # Backward and optimize
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

In [31]:
import torch
from torch import nn

m=nn.Linear(3,3,bias=False)
W=m.weight
print(W)
det=torch.det(W)
print(det)
z = torch.randn(3, 3)
print(x)
y=m(x)
print(torch.dot(y,x))



Parameter containing:
tensor([[-0.2923,  0.0250, -0.2512],
        [ 0.0650,  0.3000, -0.3059],
        [-0.3540,  0.3110, -0.2956]], requires_grad=True)
tensor(-0.0305, grad_fn=<DetLuBasedHelperBackward0>)
tensor([[1.1000, 2.2000, 3.3000],
        [1.4000, 2.5000, 3.6000],
        [1.3000, 2.3000, 3.3000]])


TypeError: dot() got an unexpected keyword argument 'axis'

In [17]:
m = nn.Linear(3, 3)
input = torch.randn(10, 3)
print(input)
output = m(input)
print(output.size())

tensor([[ 0.2469,  0.4728, -0.3868],
        [ 0.2693, -0.8485, -1.0047],
        [ 0.3464,  0.0428, -0.3292],
        [-0.5103, -0.6700, -0.9507],
        [-0.8863,  0.2683,  1.6451],
        [-1.0197, -0.2413,  0.5959],
        [ 0.6121, -2.4313, -0.5840],
        [-0.5501,  0.4592, -0.0392],
        [-2.0275,  0.5105, -1.3787],
        [-1.5137,  0.2372,  0.4769]])
torch.Size([10, 3])
